[project]
name = "nonebot-plugin-orm"
version = "0.1.0"
description = "SQLAlchemy ORM support for nonebot"
authors = [
    { name = "yanyongyu", email = "yyy@nonebot.dev" },
    { name = "ProgramRipper", email = "programripper@foxmail.com" },
]
dependencies = [
    "alembic~=1.11",
    "click~=8.1",
    "importlib-metadata~=6.8; python_version < '3.10'",
    "nonebot2~=2.0",
    "sqlalchemy~=2.0",
    "typing-extensions~=4.4; python_version < '3.12'",
]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }
keywords = ["nonebot", "orm", "sqlalchemy"]

[project.urls]
homepage = "https://github.com/nonebot/plugin-orm"
repository = "https://github.com/nonebot/plugin-orm"
documentation = "https://github.com/nonebot/plugin-orm"

[project.optional-dependencies]
default = ["aiosqlite~=0.19", "nonebot-plugin-localstore~=0.5"]

[project.entry-points.nb_scripts]
orm = "nonebot_plugin_orm.__main__:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black~=23.7",
    "isort~=5.12",
    "nonemoji~=0.1",
    "pre-commit~=3.3",
    "pycln~=2.2",
    "aiosqlite~=0.19",
]

[tool.black]
line-length = 88
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = ["typing_extensions"]

[tool.pycln]
path = "."

[tool.pyright]
pythonVersion = "3.9"
