from alembic import util
from click import ClickException


class CommandError(ClickException, util.CommandError):
    pass


class AutogenerateDiffsDetected(util.AutogenerateDiffsDetected, CommandError):
    pass
