from alembic import util
from click import ClickException


class CommandError(ClickException, util.CommandError):
    pass


class AutogenerateDiffsDetected(CommandError, util.AutogenerateDiffsDetected):
    pass
