name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"
        cache: true

    - name: Install dependencies
      run: pdm install  
